name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  isort:
    if: github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/isort.yml
  black:
    if: github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/black.yml
  build:
    if: github.event.pull_request.head.repo.full_name != github.repository
    uses: ./.github/workflows/build.yml
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.DBBS_APP_ID }}
          private-key: ${{ secrets.DBBS_APP_PRIVATE_KEY }}
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'
          token: ${{ steps.app-token.outputs.token }}
